package views;

import Model.bean.Cidade;
import Model.bean.Consulta;
import Model.bean.Grau_Risco;
import Model.bean.Item_perguntas;
import Model.bean.Item_selecionados;
import Model.bean.Pergunta;
import Model.bean.Pessoas;
import Model.bean.Sintomas;
import Model.dao.CidadeDao;
import Model.dao.ConsultaDao;
import Model.dao.Grau_RiscoDao;
import Model.dao.Item_SelecionadosDao;
import Model.dao.Item_perguntasDao;
import Model.dao.PerguntaDao;
import Model.dao.PessoasDao;
import Model.dao.SintomasDao;
import Model.dao.WebServiceCep;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bio_j
 */
public class TelaDetalhes extends javax.swing.JFrame {

    Cidade c = new Cidade();
    CidadeDao cdao = new CidadeDao();

    Pessoas p = new Pessoas();
    PessoasDao pdao = new PessoasDao();

    Sintomas s = new Sintomas();
    SintomasDao sdao = new SintomasDao();

    Grau_Risco grau = new Grau_Risco();
    Grau_RiscoDao grauDao = new Grau_RiscoDao();

    Item_selecionados i = new Item_selecionados();
    Item_SelecionadosDao idao = new Item_SelecionadosDao();

    Pergunta pp = new Pergunta();
    PerguntaDao ppdao = new PerguntaDao();

    Item_perguntas ip = new Item_perguntas();
    Item_perguntasDao ipdao = new Item_perguntasDao();

    Consulta cc = new Consulta();
    ConsultaDao ccdao = new ConsultaDao();

    FundoPanel fundo = new FundoPanel();

    public TelaDetalhes(String pessoa) {
        this.setContentPane(fundo);
        initComponents();

        iniciar_consulta(pessoa);

        Tabela_sintomas();
        Tabela_pergunta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        Consulta = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_selecionados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_perguntas = new javax.swing.JTable();
        finalizar = new javax.swing.JButton();
        idade = new javax.swing.JFormattedTextField();
        tempe = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        press = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nomee = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        resultado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abas.setBackground(new java.awt.Color(0, 153, 153));

        Consulta.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Idade");

        tabela_selecionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Descrição", "Risco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_selecionados);

        tabela_perguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Pergunta", "Resposta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela_perguntas);

        finalizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        finalizar.setText("Finalizar Avaliação ");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });

        idade.setEnabled(false);

        tempe.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Temperatura");

        press.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("Pressão");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Nome Completo");

        nomee.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setText("Outros sintomas");

        cpf.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setText("CPF");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setText("Sintomas");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("Diagnostico final");

        resultado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diagnostico do Paciente", "Com Corona", "Sem Corona" }));

        javax.swing.GroupLayout ConsultaLayout = new javax.swing.GroupLayout(Consulta);
        Consulta.setLayout(ConsultaLayout);
        ConsultaLayout.setHorizontalGroup(
            ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaLayout.createSequentialGroup()
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13)
                                .addComponent(nomee, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                .addComponent(cpf)))
                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConsultaLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(ConsultaLayout.createSequentialGroup()
                                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(38, 38, 38)
                                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tempe, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(28, 28, 28)
                                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(press, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ConsultaLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(jLabel16)
                    .addContainerGap(1178, Short.MAX_VALUE)))
        );
        ConsultaLayout.setVerticalGroup(
            ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ConsultaLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConsultaLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConsultaLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tempe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(press, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ConsultaLayout.createSequentialGroup()
                    .addGap(272, 272, 272)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(481, Short.MAX_VALUE)))
        );

        abas.addTab("Detalhes do Paciente", Consulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abas)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void iniciar_consulta(String nomepesq) {

        for (Pessoas pesq : pdao.readForNome(nomepesq)) {
            nomee.setText(pesq.getNome());
            cpf.setText(pesq.getCpf());
        }

        for (Consulta cpesq : ccdao.readForNome(nomepesq)) {
            idade.setText(cpesq.getIdade());
            tempe.setText(cpesq.getTemp());
            press.setText(cpesq.getPress());
        }

    }

    public void Tabela_sintomas() {
        DefaultTableModel modelo = (DefaultTableModel) tabela_selecionados.getModel();
        modelo.setNumRows(0);
        int codi = 0;
        for (Consulta con : ccdao.readForNome(nomee.getText())) {
            codi = con.getId();
        }
        for (Item_selecionados ii : idao.listar_sintomas(codi)) {
            modelo.addRow(new Object[]{
                ii.getId(),
                ii.getSintoma().getDescricao(),
                ii.getGrau().getDescricao(),});
        }
    }
    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed

        atualizar_consulta();
    }//GEN-LAST:event_finalizarActionPerformed
    public void atualizar_consulta() {

        if (resultado.getSelectedItem().equals("Diagnostico do Paciente")) {
            JOptionPane.showMessageDialog(null, "SELECIONE O DIAGNOSTICO");
        } else {

            if (resultado.getSelectedItem().equals("Com Corona")) {
                cc.setStatuss("POSITIVO");
            } else if (resultado.getSelectedItem().equals("Sem Corona")) {
                cc.setStatuss("NEGATIVO");
            }

            for (Consulta ccpesq : ccdao.readForNome(nomee.getText())) {
                cc.setId(ccpesq.getId());
            }
            cc.setIdade(idade.getText());
            cc.setTemp(tempe.getText());
            cc.setPress(press.getText());

            ccdao.update(cc);

            finalizar();
        }

    }

    public void finalizar() {
        JOptionPane.showMessageDialog(null, "Diagnostico Concluido");
        new PessoasCadastrada().setVisible(true);
        dispose();
    }

    public void Tabela_pergunta() {
        DefaultTableModel modelo = (DefaultTableModel) tabela_perguntas.getModel();
        modelo.setNumRows(0);

        int codii = 0;
        for (Consulta con : ccdao.readForNome(nomee.getText())) {
            codii = con.getId();
        }

        for (Item_perguntas ipp : ipdao.listar_pergunta(codii)) {
            modelo.addRow(new Object[]{
                ipp.getId(),
                ipp.getPergunta().getPergunta(),
                ipp.getResposta(),});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String nomepesq = "maria";
                new TelaDetalhes(nomepesq).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Consulta;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JTextField cpf;
    private javax.swing.JButton finalizar;
    private javax.swing.JFormattedTextField idade;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomee;
    private javax.swing.JFormattedTextField press;
    private javax.swing.JComboBox<String> resultado;
    private javax.swing.JTable tabela_perguntas;
    private javax.swing.JTable tabela_selecionados;
    private javax.swing.JFormattedTextField tempe;
    // End of variables declaration//GEN-END:variables

    class FundoPanel extends JPanel {

        private Image imagem;

        @Override
        public void paint(Graphics g) {
//pessoas.jpeg
            imagem = new ImageIcon(getClass().getResource("/imagens/telaADM.jpg")).getImage();
            g.drawImage(imagem, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }

    }

}
